# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

 
  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
    
      config.vm.box = "generic/centos8"
      node.vm.hostname = "node#{i}.k8"
      node.vm.network "private_network", ip: "192.168.56.10#{i}"
      config.vm.provider "virtualbox" do |v|  
        v.memory = "3000"
        v.cpus = "2"
      end
      config.vm.provision "file", source: "ssl/", destination: "/home/vagrant"
      node.vm.provision "ansible", inventory_path: "inventory", playbook: "main.yml"
    end
  end 
end
